# Generated by Django 2.1.3 on 2018-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20181107_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('autho', models.CharField(max_length=100, unique=True, verbose_name='作者')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
                ('lastchange', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='vip',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vip',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
