# Generated by Django 2.1.3 on 2018-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20181111_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
